create or replace view public.game_engagement_rollup as
with session_base as (
  select
    game_id,
    genre,
    count(*) as sessions,
    sum(case when completed then 1 else 0 end) as completions,
    sum(coalesce(total_seconds, 0)) as total_seconds,
    sum(restarts) as restarts,
    sum(shares) as shares,
    sum(case when completed then 0 else 1 end) as abandons
  from public.game_sessions
  join public.games on games.id = game_sessions.game_id
  where started_at >= now() - interval '7 days'
  group by game_id, genre
),
favorites_base as (
  select
    game_id,
    count(*) as favorites
  from public.favorites
  group by game_id
),
combined as (
  select
    sb.game_id,
    sb.genre,
    sb.sessions,
    sb.completions,
    sb.total_seconds,
    sb.restarts,
    sb.shares,
    sb.abandons,
    coalesce(fb.favorites, 0) as favorites
  from session_base sb
  left join favorites_base fb on fb.game_id = sb.game_id
)
select * from combined;

create table if not exists public.likability_jobs (
  id bigint generated by default as identity primary key,
  run_at timestamptz not null default now(),
  status text not null default 'started',
  details jsonb default '{}'
);
